import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/containers/Header/Header";
import { Toaster } from "react-hot-toast";
import AuthState from "@/context/AuthContext/AuthState";
import NoteState from "@/context/NoteContext/NoteState";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background-500 min-h-svh w-full flex flex-col justify-between">
        <AuthState>
          <NoteState>
            <Header />

            {children}
            <Toaster />
          </NoteState>
        </AuthState>
      </body>
    </html>
  );
}
